# Generated by Django 5.0 on 2024-01-13 10:39

from django.db import migrations



def insert_users(apps, schema_editor):
    User = apps.get_model('users', 'CustomUser')
    User.objects.create_superuser('satheesh22g', 'satheesh@gmail.com', 'satheesh22')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_users),
    ]
