from django.db import migrations

def insert_quotes(apps, schema_editor):
    Quote = apps.get_model('quotegenerator', 'Quote')
    quotes_data = [
        {'content': 'Your time is limited, don\'t waste it living someone else\'s life.', 'author': 'Steve Jobs'},
        {'content': 'Strive not to be a success, but rather to be of value.', 'author': 'Albert Einstein'},
        {'content': 'The future belongs to those who believe in the beauty of their dreams.', 'author': 'Eleanor Roosevelt'},
        {'content': 'In three words I can sum up everything I\'ve learned about life: it goes on.', 'author': 'Robert Frost'},
        {'content': 'Don\'t cry because it\'s over, smile because it happened.', 'author': 'Dr. Seuss'},
        {'content': 'Be yourself; everyone else is already taken.', 'author': 'Oscar Wilde'},
        {'content': 'Two things are infinite: the universe and human stupidity; and I\'m not sure about the universe.', 'author': 'Albert Einstein'},
        {'content': 'Be the change that you wish to see in the world.', 'author': 'Mahatma Gandhi'},
        {'content': 'No one can make you feel inferior without your consent.', 'author': 'Eleanor Roosevelt'},
        {'content': 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', 'author': 'Ralph Waldo Emerson'},
        {'content': 'Imperfection is beauty, madness is genius and it\'s better to be absolutely ridiculous than absolutely boring.', 'author': 'Marilyn Monroe'},
        {'content': 'You have within you right now, everything you need to deal with whatever the world can throw at you.', 'author': 'Brian Tracy'},
        {'content': 'The only limit to our realization of tomorrow will be our doubts of today.', 'author': 'Franklin D. Roosevelt'},
        {'content': 'You never fail until you stop trying.', 'author': 'Albert Einstein'},
        {'content': 'Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent.', 'author': 'Calvin Coolidge'},
        {'content': 'Don\'t watch the clock; do what it does. Keep going.', 'author': 'Sam Levenson'},
        {'content': 'The only way to achieve the impossible is to believe it is possible.', 'author': 'Charles Kingsleigh'},
        {'content': 'Life is really simple, but we insist on making it complicated.', 'author': 'Confucius'},
        {'content': 'Our greatest glory is not in never falling, but in rising every time we fall.', 'author': 'Confucius'},
        {'content': 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'author': 'Albert Schweitzer'},
        {'content': 'The way to get started is to quit talking and begin doing.', 'author': 'Walt Disney'},
        {'content': 'Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'author': 'Roy T. Bennett'},
        {'content': 'The only person you are destined to become is the person you decide to be.', 'author': 'Ralph Waldo Emerson'},
        {'content': 'Success is stumbling from failure to failure with no loss of enthusiasm.', 'author': 'Winston S. Churchill'},
        {'content': 'It does not matter how slowly you go, so long as you do not stop.', 'author': 'Confucius'},
        {'content': 'The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.', 'author': 'Vince Lombardi'},
        {'content': 'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.', 'author': 'Steve Jobs'},
        {'content': 'Do not wait to strike till the iron is hot, but make it hot by striking.', 'author': 'William Butler Yeats'},
        {'content': 'It is never too late to be what you might have been.', 'author': 'George Eliot'},
        {'content': 'Success usually comes to those who are too busy to be looking for it.', 'author': 'Henry David Thoreau'},
        {'content': 'The only place where success comes before work is in the dictionary.', 'author': 'Vidal Sassoon'},
        {'content': 'Believe you can and you\'re halfway there.', 'author': 'Theodore Roosevelt'},
        {'content': 'Success is getting what you want, happiness is wanting what you get.', 'author': 'W. P. Kinsella'},
        {'content': 'Don\'t be afraid to give up the good to go for the great.', 'author': 'John D. Rockefeller'},
        {'content': 'The only limit to our realization of tomorrow will be our doubts of today.', 'author': 'Franklin D. Roosevelt'},
        {'content': 'Learn as if you will live forever, live like you will die tomorrow.', 'author': 'Mahatma Gandhi'},
        {'content': 'The best way to predict the future is to create it.', 'author': 'Peter Drucker'},
        {'content': 'Your attitude, not your aptitude, will determine your altitude.', 'author': 'Zig Ziglar'},
        {'content': 'Don\'t watch the clock; do what it does. Keep going.', 'author': 'Sam Levenson'},
        {'content': 'It always seems impossible until it’s done.', 'author': 'Nelson Mandela'},
        {'content': 'Start where you are. Use what you have. Do what you can.', 'author': 'Arthur Ashe'},
        {'content': 'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.', 'author': 'Christian D. Larson'},
        {'content': 'Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'author': 'Roy T. Bennett'},
        {'content': 'Do not wait to strike till the iron is hot, but make it hot by striking.', 'author': 'William Butler Yeats'},
        {'content': 'Believe you can and you’re halfway there.', 'author': 'Theodore Roosevelt'},
        {'content': 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'author': 'Albert Schweitzer'},
        {'content': 'It does not matter how slowly you go, so long as you do not stop.', 'author': 'Confucius'},
        {'content': 'Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'author': 'Roy T. Bennett'},
        {'content': 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'author': 'Albert Schweitzer'},
        {'content': 'It does not matter how slowly you go, so long as you do not stop.', 'author': 'Confucius'},
        {'content': 'The only person you are destined to become is the person you decide to be.', 'author': 'Ralph Waldo Emerson'},
        {'content': 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'author': 'Albert Schweitzer'},
        {'content': 'The only way to do great work is to love what you do.', 'author': 'Steve Jobs'},
        {'content': 'Success is not final, failure is not fatal: It is the courage to continue that counts.', 'author': 'Winston Churchill'},
        {'content': 'Your time is limited, don’t waste it living someone else’s life.', 'author': 'Steve Jobs'},
        {'content': 'Strive not to be a success, but rather to be of value.', 'author': 'Albert Einstein'},
        {'content': 'The future belongs to those who believe in the beauty of their dreams.', 'author': 'Eleanor Roosevelt'},
        {'content': 'In three words I can sum up everything I’ve learned about life: it goes on.', 'author': 'Robert Frost'},
        {'content': 'Don’t cry because it’s over, smile because it happened.', 'author': 'Dr. Seuss'},
        {'content': 'Be yourself; everyone else is already taken.', 'author': 'Oscar Wilde'},
        {'content': 'Two things are infinite: the universe and human stupidity; and I’m not sure about the universe.', 'author': 'Albert Einstein'},
        {'content': 'Be the change that you wish to see in the world.', 'author': 'Mahatma Gandhi'},
        {'content': 'No one can make you feel inferior without your consent.', 'author': 'Eleanor Roosevelt'},
        {'content': 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', 'author': 'Ralph Waldo Emerson'},
        {'content': 'Imperfection is beauty, madness is genius and it’s better to be absolutely ridiculous than absolutely boring.', 'author': 'Marilyn Monroe'},
        {'content': 'You have within you right now, everything you need to deal with whatever the world can throw at you.', 'author': 'Brian Tracy'},
        {'content': 'The only limit to our realization of tomorrow will be our doubts of today.', 'author': 'Franklin D. Roosevelt'},
        {'content': 'You never fail until you stop trying.', 'author': 'Albert Einstein'},
        {'content': 'Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent.', 'author': 'Calvin Coolidge'},
        {'content': 'Don’t watch the clock; do what it does. Keep going.', 'author': 'Sam Levenson'},
        {'content': 'The only way to achieve the impossible is to believe it is possible.', 'author': 'Charles Kingsleigh'},
        {'content': 'Life is really simple, but we insist on making it complicated.', 'author': 'Confucius'},
        {'content': 'Our greatest glory is not in never falling, but in rising every time we fall.', 'author': 'Confucius'},
        {'content': 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'author': 'Albert Schweitzer'},
        {'content': 'The way to get started is to quit talking and begin doing.', 'author': 'Walt Disney'},
        {'content': 'Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'author': 'Roy T. Bennett'},
        {'content': 'The only person you are destined to become is the person you decide to be.', 'author': 'Ralph Waldo Emerson'},
        {'content': 'Success is stumbling from failure to failure with no loss of enthusiasm.', 'author': 'Winston S. Churchill'},
        {'content': 'It does not matter how slowly you go, so long as you do not stop.', 'author': 'Confucius'},
        {'content': 'The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.', 'author': 'Vince Lombardi'},
        {'content': 'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.', 'author': 'Steve Jobs'},
        {'content': 'Do not wait to strike till the iron is hot, but make it hot by striking.', 'author': 'William Butler Yeats'},
        {'content': 'It is never too late to be what you might have been.', 'author': 'George Eliot'},
        {'content': 'Success usually comes to those who are too busy to be looking for it.', 'author': 'Henry David Thoreau'},
        {'content': 'The only place where success comes before work is in the dictionary.', 'author': 'Vidal Sassoon'},
        {'content': 'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.', 'author': 'Christian D. Larson'},
        {'content': 'Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'author': 'Roy T. Bennett'},
        {'content': 'Do not wait to strike till the iron is hot, but make it hot by striking.', 'author': 'William Butler Yeats'},
        {'content': 'Believe you can and you’re halfway there.', 'author': 'Theodore Roosevelt'},
        {'content': 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'author': 'Albert Schweitzer'},
        {'content': 'It does not matter how slowly you go, so long as you do not stop.', 'author': 'Confucius'},
        {'content': 'Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'author': 'Roy T. Bennett'},
        {'content': 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'author': 'Albert Schweitzer'},
        {'content': 'It does not matter how slowly you go, so long as you do not stop.', 'author': 'Confucius'},
        {'content': 'The only person you are destined to become is the person you decide to be.', 'author': 'Ralph Waldo Emerson'},
        {'content': 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'author': 'Albert Schweitzer'},
        {'content': 'The only way to do great work is to love what you do.', 'author': 'Steve Jobs'},
        {'content': 'Success is not final, failure is not fatal: It is the courage to continue that counts.', 'author': 'Winston Churchill'},
        {'content': 'Your time is limited, don’t waste it living someone else’s life.', 'author': 'Steve Jobs'},
        {'content': 'Strive not to be a success, but rather to be of value.', 'author': 'Albert Einstein'},
        {'content': 'The future belongs to those who believe in the beauty of their dreams.', 'author': 'Eleanor Roosevelt'},
        {'content': 'In three words I can sum up everything I’ve learned about life: it goes on.', 'author': 'Robert Frost'},
        {'content': 'Don’t cry because it’s over, smile because it happened.', 'author': 'Dr. Seuss'},
        {'content': 'Be yourself; everyone else is already taken.', 'author': 'Oscar Wilde'},
        {'content': 'Two things are infinite: the universe and human stupidity; and I’m not sure about the universe.', 'author': 'Albert Einstein'},
        {'content': 'Be the change that you wish to see in the world.', 'author': 'Mahatma Gandhi'},
        {'content': 'No one can make you feel inferior without your consent.', 'author': 'Eleanor Roosevelt'},
        {'content': 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', 'author': 'Ralph Waldo Emerson'},
        {'content': 'Imperfection is beauty, madness is genius and it’s better to be absolutely ridiculous than absolutely boring.', 'author': 'Marilyn Monroe'},
        {'content': 'You have within you right now, everything you need to deal with whatever the world can throw at you.', 'author': 'Brian Tracy'},
        {'content': 'The only limit to our realization of tomorrow will be our doubts of today.', 'author': 'Franklin D. Roosevelt'},
        {'content': 'You never fail until you stop trying.', 'author': 'Albert Einstein'},
        {'content': 'Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent.', 'author': 'Calvin Coolidge'},
        {'content': 'Don’t watch the clock; do what it does. Keep going.', 'author': 'Sam Levenson'},
        {'content': 'The only way to achieve the impossible is to believe it is possible.', 'author': 'Charles Kingsleigh'},
        {'content': 'Life is really simple, but we insist on making it complicated.', 'author': 'Confucius'},
        {'content': 'Our greatest glory is not in never falling, but in rising every time we fall.', 'author': 'Confucius'},
        {'content': 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'author': 'Albert Schweitzer'},
        {'content': 'The way to get started is to quit talking and begin doing.', 'author': 'Walt Disney'},
        {'content': 'Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'author': 'Roy T. Bennett'},
        {'content': 'The only person you are destined to become is the person you decide to be.', 'author': 'Ralph Waldo Emerson'},
        {'content': 'Success is stumbling from failure to failure with no loss of enthusiasm.', 'author': 'Winston S. Churchill'},
        {'content': 'It does not matter how slowly you go, so long as you do not stop.', 'author': 'Confucius'},
        {'content': 'The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.', 'author': 'Vince Lombardi'},
        {'content': 'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.', 'author': 'Steve Jobs'},
        {'content': 'Do not wait to strike till the iron is hot, but make it hot by striking.', 'author': 'William Butler Yeats'},
        {'content': 'It is never too late to be what you might have been.', 'author': 'George Eliot'},
        {'content': 'Success usually comes to those who are too busy to be looking for it.', 'author': 'Henry David Thoreau'},
        {'content': 'The only place where success comes before work is in the dictionary.', 'author': 'Vidal Sassoon'},
        {'content': 'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.', 'author': 'Christian D. Larson'},
        {'content': 'Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'author': 'Roy T. Bennett'},
        {'content': 'Do not wait to strike till the iron is hot, but make it hot by striking.', 'author': 'William Butler Yeats'},
        {'content': 'Believe you can and you’re halfway there.', 'author': 'Theodore Roosevelt'},
        {'content': 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'author': 'Albert Schweitzer'}

    ]
    for data in quotes_data:
        Quote.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('quotegenerator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_quotes),
    ]
