# Generated by Django 4.2.7 on 2023-11-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('extracted_text', models.TextField()),
                ('document_type', models.CharField(max_length=10)),
            ],
        ),
    ]
